#!/bin/bash
set -e

OP_TEST_SCRIPT_URL=${OP_TEST_SCRIPT_URL-"https://raw.githubusercontent.com/redhat-openshift-ecosystem/operator-test-playbooks/d64319fdeb08f8cb0be328ab711388cc1353513b/upstream/test/oprt_cosmetics.sh"} # branch upstream-community

bash <(curl -sL $OP_TEST_SCRIPT_URL) $*
rc=$?
echo "rc=$rc"
[[ $rc -eq 0 ]] || { echo "Error: rc=$rc"; exit $rc; }
