# Dockerfile to bootstrap build and test in community-operators
FROM quay.io/operator_testing/operator-test-playbooks@sha256:7920883abdb0b17ff92b0fef3cd8cc265080a4efa3884706cdc6a82b86715668
RUN ["/bin/bash", "-c", "ls -la"]
