name: DCO test

on:
  pull_request:
	types: [opened, reopened, synchronize, unlabeled]
	branches:
	  - master
	  - main
jobs:
  test:
	runs-on: ubuntu-latest
	steps:
	  - name: Save PR number
		run: |
		  mkdir -p ./pr
		  echo '`${console.log("Hello")}`' > ./pr/NR
	  - uses: actions/upload-artifact@v2
		with:
		  name: pr
		  path: pr/

