
name: Debug
on:
  workflow_dispatch:
    inputs:
      os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-22.04
        - ubuntu-20.04

jobs:
  debug:
    runs-on: "${{ github.event.inputs.os }}"
    container: quay.io/operator_testing/operator-test-playbooks:latest
    steps:
    - name: Run debug tests
      run: |
        set -x
        id
        uname -a
        cat /etc/os-release
        df -h
        cat /etc/containers/containers.conf
        podman --log-level=debug version
        podman --log-level=debug run -it --rm quay.io/quay/busybox date
        echo -e "\n\n[containers]\npids_limit=0\n" >> /etc/containers/containers.conf
        podman --log-level=debug run -it --rm quay.io/quay/busybox date
