
name: Operator index sha sync

on: 
  workflow_dispatch:
    inputs:
      kubernetes:
        description: 'Sync index sha for kuberentes'     
        required: true
        default: '0'
      openshift:
        description: 'Sync index sha for openshift'     
        required: true
        default: '0'

env:
  OPP_CONTAINER_OPT: "-t"
  OPP_SCRIPT_ISS_URL: "https://raw.githubusercontent.com/operator-framework/community-operators/support/ci_01/ci/scripts/opp-iss.sh"
  GODEBUG: x509ignoreCN=0
  OPP_INDEX_MIRROR: 1
  OPP_MIRROR_LATEST_TAG: "v4.6"
  OPP_PRODUCTION_TYPE: "ocp"

  QUAY_API_TOKEN_OPENSHIFT_COMMUNITY_OP: ${{ secrets.QUAY_API_TOKEN_OPENSHIFT_COMMUNITY_OP }}
  QUAY_API_TOKEN_OPERATORHUBIO: ${{ secrets.QUAY_API_TOKEN_OPERATORHUBIO }}
  QUAY_RH_INDEX_PW: ${{ secrets.QUAY_RH_INDEX_PW }}
  IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
  IIB_OUTPUT_REGISTRY_TOKEN: ${{ secrets.IIB_OUTPUT_REGISTRY_TOKEN }}

jobs:
  k8s-index-sha:
    if: github.event.inputs.kubernetes == '1'
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    steps:
    - run: |
        echo "kubernetes: ${{ github.event.inputs.kubernetes }} latest"
        bash <(curl -sL $OPP_SCRIPT_ISS_URL) kubernetes latest

  o7t-index-sha:
    if: github.event.inputs.openshift == '1'
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    strategy:
      matrix:
        index-tag: [ v4.6, v4.7, v4.8 ]

      fail-fast: false
    steps:
    - run: |
        echo "openshift: ${{ github.event.inputs.openshift }} ${{ matrix.index-tag }}"
        bash <(curl -sL $OPP_SCRIPT_ISS_URL) openshift ${{ matrix.index-tag }}
